version: "3.9"

services:
  web:
    build: .
    container_name: medic_query_web
    env_file:
      - .env
    environment:
      - DB_ENGINE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-medic_query}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
      - DEBUG=${DEBUG:-false}
      - SECURE_SSL_REDIRECT=false
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_media:/app/media
      - django_logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: medic_query_db
    environment:
      - POSTGRES_DB=${DB_NAME:-medic_query}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  postgres_data:
  django_media:
  django_logs:
